version: "3.2"
services:
  persia_nats_service:
    image: nats:latest
    deploy:
      replicas: 1
          
  data_loader:
      - .docker.env
    depends_on:
      - nn_worker
      - embedding_worker
      - persia_nats_service
    image: persiasml/persia-cuda-runtime:latest
    command: REPLICA_SIZE=1 REPLICA_INDEX=0 python3 /workspace/data_loader.py
    volumes:
      - type: bind
        source: .
        target: /workspace
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nn_worker:
    env_file:
      - .docker.env
    environment:
      NCCL_SOCKET_IFNAME: eth0
      CUBLAS_WORKSPACE_CONFIG: :4096:8
    image: persiasml/persia-cuda-runtime:latest
    command: persia-launcher nn-worker /workspace/train.py 
    volumes:
      - type: bind
        source: .
        target: /workspace
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  embedding_worker:
    env_file:
      - .docker.env
    depends_on:
      - server
    image: persiasml/persia-cuda-runtime:latest
    command: persia-launcher embedding-worker --embedding-config $$PERSIA_EMBEDDING_CONFIG --global-config $$PERSIA_GLOBAL_CONFIG
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace

  server:
    env_file:
      - .docker.env
    environment:
    image: persiasml/persia-cuda-runtime:latest
    command: persia-launcher embedding-parameter-server --embedding-config $$PERSIA_EMBEDDING_CONFIG--global-config  $$PERSIA_GLOBAL_CONFIG
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: bind
        source: .
        target: /workspace